### ISSUE TITLE
Unable to turn off/on light

### ISSUE THREAD

**Issue by JS-E** [BazaJayGee66/homeassistant_cololight#33]
Hi there! Super glad someone has built this as i just installed the app and it's such garbage.

I've set up the custom component and pointed it at the hostname but i cannot seem to turn it on and off or change the brightness :'(

Is there a way i can diagnose this at all? Appreciate the help

**Comment by BazaJayGee66** [comment]
Hey @JS-E,

Are you able to confirm the following:

- Version of Home Assistant
- Version of the custom component
- Installation method (HACS vs Manual)
- Which cololight device are you trying add

Also do you see anything in the logs related to the cololight integration?

**Comment by JS-E** [comment]
Hi @BazaJayGee66,

Thanks for responding to help me with this issue

Versions are as follows:
Home Assistant 2022.12.0 - Frontend 20221207.0 - latest
Custom component v2.0.2
Installed it manually
Cololight pro hex

I will also mention that i can see it's connected to my home network from the router page so i know it's available to contact.

Nothing seems to show in the logs when i try switching the cololight on and off :/

**Comment by BazaJayGee66** [comment]
Thanks for the details.

I've been able to confirm that Cololight pro hex is working with Home Assistant 2023.6.3

To assist with debugging can you confirm the following:

1. You are able to control the device with the cololight app
2. Cololight device IP address matches with host entered in Home Assistant
3. Cololight device Firmware version
4. This [link](https://my.home-assistant.io/redirect/config_flow_start?domain=cololight) takes you your setting page to setup a new cololight device.
5. In Home Assistant, does the device status become `unavailable` after some time (grayed out)
6. If you can, in Home Assistant under the Cololight integration `Enable debug logging` (This feature might be in a new release of Home Assistant)

It may also be due to the old version of Home Assistant that you are running.

**Comment by JS-E** [comment]
Hey, thanks for getting back to me. I recently did an update to the app and home assistant and everything just started working. Not sure why as i thought homeassistant was automatically updating in the background but yeah everything is good now, i can turn it on and off and change colours easy. Excellent! Thanks very much for your work!

I know this might be a bit irrelevant for this issue, but are their plans to add in extra things like speed control or custom animation colours?

**Comment by BazaJayGee66** [comment]
> I know this might be a bit irrelevant for this issue, but are their plans to add in extra things like speed control or custom animation colours?

The integration uses the HA light extension, and thus only has the same options as what lights offer in HA. I haven't found a meaningful way to add some of these custom settings as yet.
